aliado/urls.py
from django.conf.urls import patterns, include, url
from . import views
from django.contrib.auth.decorators import login_required


urlpatterns = patterns ('aliado.views',

	#url(r'^organizacion/', 'datos_organizacion', name='organizacion' ),
	url(r'^aliado/registrar/aliado', login_required(views.RegistroAliado.as_view()), name='RegistroAliado'),
	url(r'^aliado/menu/principal', login_required(views.MenuPrincipalAliado.as_view()), name='MenuPrincipal'),
	url(r'^aliado/trae_municipios', views.trae_municipios, name='trae_municipios'),
	url(r'^aliado/trae_aldeas', views.trae_aldeas, name='trae_aldeas'),
	# url(r'^aliado/registrar/directiva', views.registrar_directiva, name='registrar_directiva'),
	# url(r'^aliado/registrar/rsc_rse', views.registrar_rsc_rse, name='registrar_rsc_rse'),
	# url(r'^aliado/registrar/rubros_inversion', views.registrar_rubros_inversion, name='registrar_rubros_inversion'),
	)


aliadosxeducacion/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.views.generic.base import TemplateView
from django.contrib.auth.views import login

urlpatterns = [
    # Examples:
    # url(r'^$', 'aliadosxeducacion.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),


   # url(r'^login/$', 'django.contrib.auth.views.login'),
   	url(r'^$', 'aliadosxeducacion.views.login_page', name="login"),
   	#url(r'^accounts/login/$', 'aliadosxeducacion.views.login_page', name="login2"), #Hace que si el usuario no esta logueado lo redirija al login 
   	url(r'^logout/$', 'aliadosxeducacion.views.logout_view', name="logout"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('aliado.urls')),
    url(r'^cuentas/', include('cuentas.urls')),

    
]

aliado/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class TipoAliado (models.Model):
    nombre = models.CharField(max_length=120)
    abreviatura = models.CharField(max_length=20, null=True, blank=True)

    def  __unicode__(self):
        return u'%s' % (self.nombre)


class RubroInversionEduca (models.Model):
    nombre = models.CharField(max_length=120)
    abreviatura = models.CharField(max_length=20, null=True, blank=True)

    def  __unicode__(self):
        return u'%s, %s' % (self.nombre)

class OpcionRubroEduc(models.Model):
    nombre = models.CharField(max_length=120)
    rubro = models.ForeignKey(RubroInversionEduca)
    ejemplo = models.CharField(max_length=120, null=True, blank=True)

    def __unicode__ (self):
        return u'%s, %s, %s' %(self.nombre, self.rubro, self.ejemplo)

class RubroEmpresa(models.Model):
    nombre = models.CharField(max_length=120)
    abreviatura = models.CharField(max_length=20, null=True, blank=True)

    def  __unicode__(self):
        return u'%s' % (self.nombre)

class Departamento(models.Model):
    codigo = models.CharField(max_length=2, unique=True, help_text=u'Código Oficial del Departamento')
    nombre = models.CharField(max_length=128, unique=True, help_text='Nombre del Departamento')
        
    def __unicode__(self):
        return u'%s' % (self.nombre)

    #para el admin
    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'


class Municipio(models.Model):
    codigo = models.CharField(max_length=2, help_text=u'Código Oficial del municipio en el departamento')
    nombre = models.CharField(max_length=128, help_text='Nombre del Municipio')
    departamento = models.ForeignKey(Departamento, help_text='Departamento en el cual se encuentra ubicado')

    def natural_key(self):
        return u'%s | %s' % (self.codigo,self.nombre)
        
    def __unicode__(self):
        if (len(str(self.codigo)) < 2):
            codigo = '0' + str(self.codigo)
        else:
            codigo = str(self.codigo)

        return u'' + codigo + ' | ' + self.nombre

    class Meta:
        verbose_name = 'Municipio'
        verbose_name_plural = 'Municipios'
        unique_together = (("codigo", "departamento"),)


class Aldea(models.Model):
    codigo = models.CharField(max_length=3, help_text=u'Código Oficial de la aldea')
    nombre = models.CharField(max_length=128, help_text= u'Nombre de la Aldea')
    municipio = models.ForeignKey(Municipio, help_text=u'Municipio donde se encuentra ubicada la aldea')

    def natural_key(self):
        return u'%s | %s' % (self.codigo,self.nombre)
        
    def __unicode__(self):
        if (len(str(self.codigo)) < 2):
            codigo = '00' + str(self.codigo)
        else:
            if (len(str(self.codigo)) < 3):
                codigo = '0' + str(self.codigo)
            else:
                codigo = str(self.codigo)

        return u'%s | %s ' % (codigo,self.nombre)

    class Meta:
        verbose_name = 'Aldea'
        verbose_name_plural = 'Aldeas'
        #unique_together = (("codigo", "municipio"),)



def url(obj, filename):
        ruta = "documentos/%s/%s"%(obj.usuario_creador, obj.logo)
        return ruta

class Aliado (models.Model):
    nombre_comercial = models.CharField(max_length=150, null=True, blank=True)
    
    razon_social = models.CharField(max_length=150, null=True, blank=True)
    rtn_aliado = models.CharField(unique = True, null=True, blank=True, max_length=14)
    rubro_aliado = models.ForeignKey(RubroEmpresa, null=True, blank=True)
    direccion = models.CharField(max_length=200, null=True, blank=True)
    correo = models.CharField(max_length=50, null=True, blank=True)
    telefono = models.CharField(null=True, blank=True, max_length = 8)
    departamento = models.ForeignKey(Departamento, null=True, blank=True)
    municipio = models.ForeignKey(Municipio, null=True, blank=True)
    aldea = models.ForeignKey(Aldea, null=True, blank=True)
    logo =  models.ImageField(upload_to="url", help_text=u'Seleccione el logo de la empresa', verbose_name=u'Logo:',null=True, blank=True )
    tipo_aliado = models.ForeignKey(TipoAliado, null=True, blank=True)
    rsc_rse = models.BooleanField(default=False) #True == RSC
    rtn_fundacion = models.CharField(null=True, blank=True, max_length=14)
    nombre_fundacion = models.CharField(max_length=150, null=True, blank=True)
    direccion_fundacion = models.CharField(max_length=200, null=True, blank=True)
    usuario_creador = models.ForeignKey(User, related_name='persona_creador')
    usuario_modifico = models.ForeignKey(User, related_name='persona_modificador')
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)

    def __unicode__ (self):
        return u'%s, %s, %s, %s, %s, %s, %s, %s, %s, %s' %(self.razon_social, self.rtn_aliado, 
            self.rubro_aliado, self.departamento, self.municipio, self.aldea, self.tipo_aliado, self.rsc_rse, 
            self.rtn_fundacion, self.nombre_fundacion) 

TITULO_DIRECTIVA = (
    (1, u'ING.'), 
    (2, u'LIC.'),
    (3, u'PHD.'),
    (4, u'MSC.'), 
    (5, u'SRA.' ),
    (6, u'SR.'),

)

class DirectivaAliado(models.Model):
    aliado = models.ForeignKey(Aliado, related_name = 'aliado_directivaaliado')
    titulo = models.CharField(choices =TITULO_DIRECTIVA, max_length=7)
    nombre = models.CharField(max_length=150)
    cargo = models.CharField(max_length= 200)
    correo = models.CharField(max_length=50)
    telefono = models.IntegerField(null=True, blank=True)
    celular = models.CharField(null=True, blank=True, max_length=14)
    contacto_rsc_rse = models.BooleanField(default=False)
    contacto_primario = models.BooleanField(default=True)
    usuario_creador = models.ForeignKey(User, related_name='persona_creo_directiva', null=True, blank=True)
    usuario_modifico = models.ForeignKey(User, related_name='persona_modifico_directiva', null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    fecha_modificacion = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __unicode__ (self):
        return u'%s, %s, %s, %s, %s' %(self.aliado, self.nombre, self.cargo, 
            self.contacto_rsc_rse, self.contacto_primario)

class Periodo (models.Model):
    aliado = models.ForeignKey(Aliado, related_name = 'aliado_periodo')
    periodo = models.IntegerField()
    fecha_inicio = models.DateField(auto_now_add=True)
    fecha_final = models.DateField( )
    presupuesto_minimo = models.DecimalField(max_digits=20, decimal_places=2)
    presupuesto_maximo = models.DecimalField(max_digits=20, decimal_places=2)
    usuario_creador = models.ForeignKey(User, related_name='persona_creo_periodo', null=True, blank=True)
    usuario_modifico = models.ForeignKey(User, related_name='persona_modifico_periodo', null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    fecha_modificacion = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __unicode__ (self):
        return u'%s, %s, %s, %s, %s, %s' %(self.aliado, self.periodo, self.fecha_inicio, 
            self.fecha_final, self.presupuesto_minimo, self.presupuesto_maximo)

class RubroEducaAliado (models.Model):
    aliado = models.ForeignKey(Aliado, related_name = 'aliado_rubroaliado')
    rubro_inversion_educac = models.ForeignKey(RubroInversionEduca)

    def __unicode__ (self):
        return u'%s, %s' %(self.aliado, self.rubro_inversion_educac)

class PeriodoRubroEduca(models.Model):
    rubro_educ_aliado = models.ForeignKey(RubroEducaAliado)
    periodo = models.ForeignKey(Periodo)
    porcentaje = models.DecimalField(max_digits=3, decimal_places=2)

    def __unicode__(self): 
        return u'%s, %s, %s' %(self.rubro_educ_aliado, self.periodo, self.porcentaje)


class UsuariosAliado (models.Model):
    aliado = models.ForeignKey(Aliado, related_name='usuario_aliado')
    usuario = models.ForeignKey(User, related_name = 'usuarioaliado_user')


# AL CREAR USUARIO SI ENCUENTRA EL RTN, GUARDA USUARIO ALIADO, Y LUEGO MANDA AL MENU, SI NO ENCUENTRA EL RTN LO MANDA DE 
#UN SOLO A REGISTRAR EL ALIADO Y HACE EL GUARDADO NORMAL Y AGREGAR EL USUARIO CREADOR A USUARIOS ALIADO, 
#AGREGAR EL GUARDADO D USUARIOSALIADO EN LA VIEW DE REGISTRAR ALIADO







            

aliadosxeducacion/forms.py
# -*- coding: utf-8 -*-
from django import forms

class LoginForm (forms.Form):

	username = forms.CharField()
	clave = forms.CharField(widget = forms.PasswordInput())

cuentas/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User

from aliado.models import *

class UserProfile(forms.Form):

	usuario = forms.CharField(min_length=5)
	email = forms.EmailField()
	password = forms.CharField(min_length=5, widget=forms.PasswordInput())
	repetir_password = forms.CharField(min_length=5,widget=forms.PasswordInput())
	nombre = forms.CharField()
	apellido = forms.CharField()

	usuario = forms.CharField(
	min_length=5,
	widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Escriba su Nombre de Usuario'}))

	email = forms.EmailField(
		widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder':'Escriba su Correo Electrónico'}))

	nombre = forms.CharField(
		widget = forms.TextInput(attrs = {'class': 'form-control','placeholder':'Escriba su Nombre'}))

	apellido = forms.CharField(
		widget= forms.TextInput(attrs = {'class': 'form-control', 'placeholder':'Escriba su Apellido'}))
	
	rtn_aliado = forms.CharField(
		widget= forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'RTN de la Empresa' }))
	

	password = forms.CharField(
		min_length=5,
		widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Escriba su Contraseña' }))

	repetir_password = forms.CharField(
		min_length=5,
		widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirme su Contraseña'}))
	   

	def clean_usuario(self):
		
		usuario = self.cleaned_data['usuario']
		
		if User.objects.filter(username=usuario):
			raise forms.ValidationError('Nombre de usuario ya registrado.')
		return usuario

	def clean_email(self):
		
		email = self.cleaned_data['email']
		if User.objects.filter(email=email):
			raise forms.ValidationError('Ya existe un email igual en la db.')
		return email

	def clean_repetir_password(self):
		
		"""Comprueba que password y repetir_password sean iguales."""
		password = self.cleaned_data['password']
		repetir_password = self.cleaned_data['repetir_password']
		
		if password != repetir_password:
			
			raise forms.ValidationError('Las contraseñas no coinciden.')
		else:
			

			return repetir_password



class SomeForm(forms.Form):
	name = forms.CharField(error_messages={'required':'Error Missing Field , Please Fill this Field'})


class DirectivaFormulario(forms.Form):

	class Meta:
		model = DirectivaAliado
		exclude = ['usuario_creador', 'usuario_modifico', 'aliado', 'contacto_rsc_rse', 'contacto_primario']

class AliadoFormulario(forms.Form):
	
	departamento = forms.ModelChoiceField(label="Departamento ", queryset=Departamento.objects.all())
	tipo_aliado = forms.ModelChoiceField(label = "Tipo de Aliado", queryset = TipoAliado.objects.all().order_by('nombre'))
	
	class Meta:
		model = Aliado
		fields = ['nombre_comercial', 'razon_social','rtn_aliado', 'direccion', 'correo',
		'telefono',  'logo', 'tipo_aliado', 'rubro_aliado', 'departamento', 'municipio', 
		'aldea' ,'rsc_rse', 'rtn_fundacion', 'nombre_fundacion', 'direccion_fundacion']

		exclude = ['usuario_creador', 'usuario_modifico', 'fecha_creacion', 'fecha_modifico']

aliadosxeducacion/views.py
# -*- coding: utf-8 -*-
from django.template import RequestContext
from django.shortcuts import render_to_response, render
from aliadosxeducacion.forms import LoginForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from django.template.loader import get_template
from aliado.models import UsuariosAliado

def login_page(request):

	message= None 
	form = LoginForm(request.POST)
	
	if request.method == "POST":
		form = LoginForm(request.POST)
		error ={}
		if form.is_valid():
			print 'valido'
			username = request.POST['username']
			password = request.POST.get('clave')
			print 'username', username, 'password', password
			user = authenticate(username=username, password=password)
			
			if  user is not None:
				try:
					if user.is_active: 
						login(request, user)
						
						aliado = UsuariosAliado.objects.filter(usuario=user.id)
						
						if aliado:
							print 'verdadero'
							return render(request, 'menu_principal_aliado.html')
						else:
							print 'retorna'
							return HttpResponseRedirect('aliado/registrar/aliado/')
					else:
						
						message = "Usuario Inactivo"
				except Exception, e:
					print 'error:', e
					message= ("Error del Sistema") 

					return render_to_response( 'login.html', {'message':message, 'form':form}, context_instance = RequestContext(request))
					
			else:
				message = "Nombre de Usuario y/o Contraseña equivocados"
		else:
			print 'else'
			return render_to_response( 'login.html', {'message':message, 'form':form}, context_instance = RequestContext(request))
	elif request.method == "GET":
		form = LoginForm()
		return render_to_response( 'login.html', {'message':message, 'form':form}, context_instance = RequestContext(request))
	return render_to_response( 'login.html', {'message':message, 'form':form}, context_instance = RequestContext(request))

#@login_required(login_url = '/login')
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

aliadosxeducacion/templates/base_login.html
<!DOCTYPE html>
<html lang="en">
    <head>{% block head %}
        <meta charset="utf-8" />
         <title>{% block titulo %}  {% endblock %} </title>

        <meta name="description" content="User login page" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <!-- basic styles -->

        <link href="{{STATIC_URL}}assets/css/bootstrap.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="{{STATIC_URL}}assets/css/font-awesome.min.css" />

        <!-- page specific plugin styles -->

        <!-- fonts -->

        <link rel="stylesheet" href="{{STATIC_URL}}assets/css/ace-fonts.css" />

        <!-- ace styles -->

        <link rel="stylesheet" href="{{STATIC_URL}}assets/css/ace.min.css" />
        <link rel="stylesheet" href="{{STATIC_URL}}assets/css/ace-rtl.min.css" />

       
    {% endblock head %}</head>



    <body class="login-layout"> {% block body %}
        <div class="main-container">
            <div class="main-content">
                <div class="row">
                    <div class="col-md-9 col-md-offset-1">

                        <div class="login-container">
                          
                                <h4 class="blue" style="width:500px" align="center" >&copy;Aliados x Educación</h4>
                            

                            <div class="space-6"></div>

                            <div class="position-relative" >
                                <div id="login-box" class="login-box visible widget-box no-border" style="width:500px; height:auto;" >
                                    <div class="widget-body" >
                                        <div class="widget-main">
                                        <center>
                                            <img src="{{STATIC_URL}}assets/images/LOGO_AXE.png" alt="Aliados por la Educación"
                                            width="225" height="118" align="center"  border="0">
                                        </center>  

                                            <div class="space-6"></div>

                                            {% block formulario %}                            
                                            {% endblock formulario %}

                                                                            
                                    {% block formulario_registro %}  
                                    {% endblock formulario_registro %}

                                            
                                        </div>
                                    </div><!-- /widget-body -->
                                </div><!-- /login-box -->

                                <div id="forgot-box" class="forgot-box widget-box no-border">
                                    <div class="widget-body">
                                        <div class="widget-main">
                                            <h4 class="header red lighter bigger">
                                                <i class="icon-key"></i>
                                                Recuperar Contraseña
                                            </h4>

                                            <div class="space-6"></div>
                                            <p>
                                                Ingrese su correo electrónico para recibir indicaciones
                                            </p>

                                            <form>
                                                <fieldset>
                                                    <label class="block clearfix">
                                                        <span class="block input-icon input-icon-right">
                                                            <input type="email" class="form-control" placeholder="Email" />
                                                            <i class="icon-envelope"></i>
                                                        </span>
                                                    </label>

                                                    <div class="clearfix">
                                                        <button type="button" class="width-35 pull-right btn btn-sm btn-danger">
                                                            <i class="icon-lightbulb"></i>
                                                            Send Me!
                                                        </button>
                                                    </div>
                                                </fieldset>
                                            </form>
                                        </div><!-- /widget-main -->

                                        <div class="toolbar center">
                                            <a href="#" onclick="show_box('login-box'); return false;" class="back-to-login-link">
                                                Volver al login
                                                <i class="icon-arrow-right"></i>
                                            </a>
                                        </div>
                                    </div><!-- /widget-body -->
                                </div><!-- /forgot-box -->

                                
                                <div id="signup-box" class="signup-box widget-box no-border">
                                    <div class="widget-body">
                                        <div class="widget-main">
                                            <h4 class="header green lighter bigger">
                                                <i class="icon-group blue"></i>
                                               Registro de Nuevo Usuario
                                            </h4>

                                            <div class="space-6"></div>
                                            <p> Ingrese su Información: </p>

                                            <form method="post" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <fieldset>
                                                    <label class="block clearfix">
                                                        <span class="block input-icon input-icon-right">
                                                            <input type="email" class="form-control" id="id_email" name="email" placeholder="Email" />
                                                            <i class="icon-envelope"></i>
                                                        </span>
                                                    </label>

                                                    <label class="block clearfix">
                                                        <span class="block input-icon input-icon-right">
                                                            <input type="text" class="form-control" id="id_username" name="username"  placeholder="Username" />
                                                            <i class="icon-user"></i>
                                                        </span>
                                                    </label>


                                                     <label class="block clearfix">
                                                        <span class="block input-icon input-icon-right">
                                                            <input type="text" class="form-control" id="id_nombre" name="nombre"  placeholder="Nombre del encargado" />
                                                            <i class="icon-user"></i>
                                                        </span>
                                                    </label>

                                                     <label class="block clearfix">
                                                        <span class="block input-icon input-icon-right">
                                                            <input type="text" class="form-control" id="id_apellido" name="apellido"  placeholder="Apellido del encargado" />
                                                            <i class="icon-user"></i>
                                                        </span>
                                                    </label>


                                                    <label class="block clearfix">
                                                        <span class="block input-icon input-icon-right">
                                                            <input type="password" class="form-control" id="id_password" name="password" placeholder="Password" />
                                                            <i class="icon-lock"></i>
                                                        </span>
                                                    </label>

                                                    <label class="block clearfix">
                                                        <span class="block input-icon input-icon-right">
                                                            <input type="password" class="form-control" id="id_password2" name="password2" placeholder="Repeat password" />
                                                            <i class="icon-retweet"></i>
                                                        </span>
                                                    </label>

                                                    <div class="space-24"></div>

                                                    <div class="clearfix">
                                                        <button type="reset" class="width-30 pull-left btn btn-sm">
                                                            <i class="icon-refresh"></i>
                                                            Reset
                                                        </button>

                                                        <button type="submit"  class="width-65 pull-right btn btn-sm btn-success">
                                                            Registrar
                                                            <i class="icon-arrow-right icon-on-right"></i>
                                                        </button>
                                                    </div>
                                                </fieldset>
                                            </form>
                                        </div>

                                        <div class="toolbar center">
                                            <a href="#" onclick="show_box('login-box'); return false;" class="back-to-login-link">
                                                <i class="icon-arrow-left"></i>
                                                Back to login
                                            </a>
                                        </div>
                                    </div><!-- /widget-body -->
                                </div><!-- /signup-box -->

                                
                            </div><!-- /position-relative -->
                        </div>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div>
        </div><!-- /.main-container -->

        <!-- basic scripts -->

        <!--[if !IE]> -->

        <script type="text/javascript">
            window.jQuery || document.write("<script src='{{STATIC_URL}}assets/js/jquery-2.0.3.min.js'>"+"<"+"/script>");
        </script>

        <!-- <![endif]-->
  

        <script type="text/javascript">
            if("ontouchend" in document) document.write("<script src='{{STATIC_URL}}assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
        </script>

        <!-- inline scripts related to this page -->

        <script type="text/javascript">
            function show_box(id) {
             jQuery('.widget-box.visible').removeClass('visible');
             jQuery('#'+id).addClass('visible');
            }
        </script>
    {% endblock body %}</body>

    {% block script %}
    {% endblock script %}
        
    {% block js %}
    {% endblock js %}
</html>

aliadosxeducacion/templates/login.html
{% extends "base_login.html" %}

{% block titulo %}LOGIN{% endblock titulo%} 

{% block formulario %}

  

  {% if message %}
    <b>{{message}}</b>
  {% endif %}

<div class="form-group" align="left" >
  <form action="" method="POST" class="form-horizontal" >
    {% csrf_token %}
    <br>
    {{form.as_p}}
    <input class="btn btn-default" type="submit" value="Login" ></input>

  </form>
</div>
{% endblock formulario %}

 {% block formulario_registro %}                       
    </div><!-- /widget-main -->

    <div class="toolbar clearfix">
    <div>
        <a href="#" onclick="show_box('forgot-box'); return false;" class="forgot-password-link">
            <i class="icon-arrow-left"></i>
            ¡Olvidé mi Contraseña!
        </a>
    </div>
    <div>
        <a href="{% url 'registro_usuario' %}" class="user-signup-link">
           Crear Usuario <i class="icon-arrow-right"></i>
        </a>
    </div>



{% endblock formulario_registro %}

{% block js %} 
    <script type="text/javascript">
        $('input').addClass('form-control')
        $('select').addClass('form-control')
    </script>
{% endblock js %}
	