aliado/urls.py
from django.conf.urls import patterns, include, url
from . import views
from django.contrib.auth.decorators import login_required


urlpatterns = patterns ('aliado.views',

	#url(r'^organizacion/', 'datos_organizacion', name='organizacion' ),
	url(r'^aliado/registrar/aliado', login_required(views.RegistroAliado.as_view()), name='RegistroAliado'),
	url(r'^aliado/menu/principal', login_required(views.MenuPrincipalAliado.as_view()), name='MenuPrincipal'),
	url(r'^aliado/trae_municipios', views.trae_municipios, name='trae_municipios'),
	url(r'^aliado/trae_aldeas', views.trae_aldeas, name='trae_aldeas'),
	# url(r'^aliado/registrar/directiva', views.registrar_directiva, name='registrar_directiva'),
	# url(r'^aliado/registrar/rsc_rse', views.registrar_rsc_rse, name='registrar_rsc_rse'),
	# url(r'^aliado/registrar/rubros_inversion', views.registrar_rubros_inversion, name='registrar_rubros_inversion'),
	)


aliado/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class TipoAliado (models.Model):
    nombre = models.CharField(max_length=120)
    abreviatura = models.CharField(max_length=20, null=True, blank=True)

    def  __unicode__(self):
        return u'%s' % (self.nombre)


class RubroInversionEduca (models.Model):
    nombre = models.CharField(max_length=120)
    abreviatura = models.CharField(max_length=20, null=True, blank=True)

    def  __unicode__(self):
        return u'%s, %s' % (self.nombre)

class OpcionRubroEduc(models.Model):
    nombre = models.CharField(max_length=120)
    rubro = models.ForeignKey(RubroInversionEduca)
    ejemplo = models.CharField(max_length=120, null=True, blank=True)

    def __unicode__ (self):
        return u'%s, %s, %s' %(self.nombre, self.rubro, self.ejemplo)

class RubroEmpresa(models.Model):
    nombre = models.CharField(max_length=120)
    abreviatura = models.CharField(max_length=20, null=True, blank=True)

    def  __unicode__(self):
        return u'%s' % (self.nombre)

class Departamento(models.Model):
    codigo = models.CharField(max_length=2, unique=True, help_text=u'Código Oficial del Departamento')
    nombre = models.CharField(max_length=128, unique=True, help_text='Nombre del Departamento')
        
    def __unicode__(self):
        return u'%s' % (self.nombre)

    #para el admin
    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'


class Municipio(models.Model):
    codigo = models.CharField(max_length=2, help_text=u'Código Oficial del municipio en el departamento')
    nombre = models.CharField(max_length=128, help_text='Nombre del Municipio')
    departamento = models.ForeignKey(Departamento, help_text='Departamento en el cual se encuentra ubicado')

    def natural_key(self):
        return u'%s | %s' % (self.codigo,self.nombre)
        
    def __unicode__(self):
        if (len(str(self.codigo)) < 2):
            codigo = '0' + str(self.codigo)
        else:
            codigo = str(self.codigo)

        return u'' + codigo + ' | ' + self.nombre

    class Meta:
        verbose_name = 'Municipio'
        verbose_name_plural = 'Municipios'
        unique_together = (("codigo", "departamento"),)


class Aldea(models.Model):
    codigo = models.CharField(max_length=3, help_text=u'Código Oficial de la aldea')
    nombre = models.CharField(max_length=128, help_text= u'Nombre de la Aldea')
    municipio = models.ForeignKey(Municipio, help_text=u'Municipio donde se encuentra ubicada la aldea')

    def natural_key(self):
        return u'%s | %s' % (self.codigo,self.nombre)
        
    def __unicode__(self):
        if (len(str(self.codigo)) < 2):
            codigo = '00' + str(self.codigo)
        else:
            if (len(str(self.codigo)) < 3):
                codigo = '0' + str(self.codigo)
            else:
                codigo = str(self.codigo)

        return u'%s | %s ' % (codigo,self.nombre)

    class Meta:
        verbose_name = 'Aldea'
        verbose_name_plural = 'Aldeas'
        #unique_together = (("codigo", "municipio"),)



def url(obj, filename):
        ruta = "documentos/%s/%s"%(obj.usuario_creador, obj.logo)
        return ruta

class Aliado (models.Model):
    nombre_comercial = models.CharField(max_length=150, null=True, blank=True)
    
    razon_social = models.CharField(max_length=150, null=True, blank=True)
    rtn_aliado = models.CharField(unique = True, null=True, blank=True, max_length=14)
    rubro_aliado = models.ForeignKey(RubroEmpresa, null=True, blank=True)
    direccion = models.CharField(max_length=200, null=True, blank=True)
    correo = models.CharField(max_length=50, null=True, blank=True)
    telefono = models.CharField(null=True, blank=True, max_length = 8)
    departamento = models.ForeignKey(Departamento, null=True, blank=True)
    municipio = models.ForeignKey(Municipio, null=True, blank=True)
    aldea = models.ForeignKey(Aldea, null=True, blank=True)
    logo =  models.ImageField(upload_to="url", help_text=u'Seleccione el logo de la empresa', verbose_name=u'Logo:',null=True, blank=True )
    tipo_aliado = models.ForeignKey(TipoAliado, null=True, blank=True)
    rsc_rse = models.BooleanField(default=False) #True == RSC
    rtn_fundacion = models.CharField(null=True, blank=True, max_length=14)
    nombre_fundacion = models.CharField(max_length=150, null=True, blank=True)
    direccion_fundacion = models.CharField(max_length=200, null=True, blank=True)
    usuario_creador = models.ForeignKey(User, related_name='persona_creador')
    usuario_modifico = models.ForeignKey(User, related_name='persona_modificador')
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)

    def __unicode__ (self):
        return u'%s, %s, %s, %s, %s, %s, %s, %s, %s, %s' %(self.razon_social, self.rtn_aliado, 
            self.rubro_aliado, self.departamento, self.municipio, self.aldea, self.tipo_aliado, self.rsc_rse, 
            self.rtn_fundacion, self.nombre_fundacion) 

TITULO_DIRECTIVA = (
    (1, u'ING.'), 
    (2, u'LIC.'),
    (3, u'PHD.'),
    (4, u'MSC.'), 
    (5, u'SRA.' ),
    (6, u'SR.'),

)

class DirectivaAliado(models.Model):
    aliado = models.ForeignKey(Aliado, related_name = 'aliado_directivaaliado')
    titulo = models.CharField(choices =TITULO_DIRECTIVA, max_length=7)
    nombre = models.CharField(max_length=150)
    cargo = models.CharField(max_length= 200)
    correo = models.CharField(max_length=50)
    telefono = models.IntegerField(null=True, blank=True)
    celular = models.CharField(null=True, blank=True, max_length=14)
    contacto_rsc_rse = models.BooleanField(default=False)
    contacto_primario = models.BooleanField(default=True)
    usuario_creador = models.ForeignKey(User, related_name='persona_creo_directiva', null=True, blank=True)
    usuario_modifico = models.ForeignKey(User, related_name='persona_modifico_directiva', null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    fecha_modificacion = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __unicode__ (self):
        return u'%s, %s, %s, %s, %s' %(self.aliado, self.nombre, self.cargo, 
            self.contacto_rsc_rse, self.contacto_primario)

class Periodo (models.Model):
    aliado = models.ForeignKey(Aliado, related_name = 'aliado_periodo')
    periodo = models.IntegerField()
    fecha_inicio = models.DateField(auto_now_add=True)
    fecha_final = models.DateField( )
    presupuesto_minimo = models.DecimalField(max_digits=20, decimal_places=2)
    presupuesto_maximo = models.DecimalField(max_digits=20, decimal_places=2)
    usuario_creador = models.ForeignKey(User, related_name='persona_creo_periodo', null=True, blank=True)
    usuario_modifico = models.ForeignKey(User, related_name='persona_modifico_periodo', null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    fecha_modificacion = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __unicode__ (self):
        return u'%s, %s, %s, %s, %s, %s' %(self.aliado, self.periodo, self.fecha_inicio, 
            self.fecha_final, self.presupuesto_minimo, self.presupuesto_maximo)

class RubroEducaAliado (models.Model):
    aliado = models.ForeignKey(Aliado, related_name = 'aliado_rubroaliado')
    rubro_inversion_educac = models.ForeignKey(RubroInversionEduca)

    def __unicode__ (self):
        return u'%s, %s' %(self.aliado, self.rubro_inversion_educac)

class PeriodoRubroEduca(models.Model):
    rubro_educ_aliado = models.ForeignKey(RubroEducaAliado)
    periodo = models.ForeignKey(Periodo)
    porcentaje = models.DecimalField(max_digits=3, decimal_places=2)

    def __unicode__(self): 
        return u'%s, %s, %s' %(self.rubro_educ_aliado, self.periodo, self.porcentaje)


class UsuariosAliado (models.Model):
    aliado = models.ForeignKey(Aliado, related_name='usuario_aliado')
    usuario = models.ForeignKey(User, related_name = 'usuarioaliado_user')


# AL CREAR USUARIO SI ENCUENTRA EL RTN, GUARDA USUARIO ALIADO, Y LUEGO MANDA AL MENU, SI NO ENCUENTRA EL RTN LO MANDA DE 
#UN SOLO A REGISTRAR EL ALIADO Y HACE EL GUARDADO NORMAL Y AGREGAR EL USUARIO CREADOR A USUARIOS ALIADO, 
#AGREGAR EL GUARDADO D USUARIOSALIADO EN LA VIEW DE REGISTRAR ALIADO







            

aliado/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.forms import ModelForm
from aliado.models import *

class AliadoFormulario(ModelForm):
	
	departamento = forms.ModelChoiceField(label="Departamento ", queryset=Departamento.objects.all())
	tipo_aliado = forms.ModelChoiceField(label = "Tipo de Aliado", queryset = TipoAliado.objects.all().order_by('nombre'))
	
	class Meta:
		model = Aliado
		fields = ['nombre_comercial', 'razon_social','rtn_aliado', 'direccion', 'correo',
		'telefono',  'logo', 'tipo_aliado', 'rubro_aliado', 'departamento', 'municipio', 
		'aldea' ,'rsc_rse', 'rtn_fundacion', 'nombre_fundacion', 'direccion_fundacion']

		exclude = ['usuario_creador', 'usuario_modifico', 'fecha_creacion', 'fecha_modifico']

		
		#QUITAR DEPARTAMENTO ALDEA Y MUNICIPIO!!!!!!!!!!!!!!!!!!

class LogoForm(ModelForm):
	title  =  forms.CharField ( max_length = 50 ) 
	file  =  forms.FileField ()

	class Meta: 
		model = Aliado

		fields = ['logo']
		exclude = ['nombre_comercial', 'razon_social','rtn_aliado', 'direccion', 'correo',
		'telefono',  'tipo_aliado', 'rubro_aliado', 'departamento', 'municipio', 'aldea' ,'rsc_rse', 'rtn_fundacion', 'nombre_fundacion', 'direccion_fundacion']


class DirectivaFormulario(ModelForm):

	class Meta:
		model = DirectivaAliado
		exclude = ['usuario_creador', 'usuario_modifico', 'aliado', 'contacto_rsc_rse', 'contacto_primario']
	

class RubroInversionEducaForm(ModelForm):

	class Meta:
		model = RubroInversionEduca
		fields = '__all__'
		

aliado/templates/base.html
<!DOCTYPE html> 
<html>

    <head> {% block head %}
   		<meta charset="utf-8" />
        <title>{% block titulo %}  {% endblock %} </title>

        <meta name="description" content="User login page" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <!-- basic styles -->

        <link href="{{STATIC_URL}}assets/css/bootstrap.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="{{STATIC_URL}}assets/css/font-awesome.min.css" />

        <!-- fonts -->

        <link rel="stylesheet" href="{{STATIC_URL}}assets/css/ace-fonts.css" />

        <!-- ace styles -->

        <link rel="stylesheet" href="{{STATIC_URL}}assets/css/ace.min.css" />
        <link rel="stylesheet" href="{{STATIC_URL}}assets/css/ace-rtl.min.css" />
       
     {%endblock head%} </head>



    <body>
        {% block content %}
        {% endblock %} 
    </body> 
</html>

aliado/templates/menu_principal_aliado.html
{% extends "base_menu_principal_aliado.html" %}

aliado/templates/registrar_datos_rsc_rse.html
{% extends "base_registro_aliado.html" %}

{% load staticfiles %}

{% block form %} 

	{% csrf_token %}


	<fieldset><h2 align="center"> <strong> Información RSC/RSE </strong></h2></fieldset><br>

<div class="page-content">
	<div class="row" >
		<div class="col-md-9 col-md-offset-2" >
			<form method="post" class="form-group">
				<div class="form-group estilo1" >
					<label class= "col-md-6" >
						<div class="col-md-6 control-label no-padding-right">
							<input name="radio" id="radio_rsc" type="radio" class="col-md-6 col-md-5 " value="muestra" >
							<span class="lbl"> RSC</span>
						</div>
					</label>
					<label class= "col-md-6" >
						<div class="col-md-6 control-label no-padding-right">
							<input name="radio" type="radio" class="col-md-6 col-md-5" value="oculta">
							<span class="lbl"> RSE </span>
						</div>
					</label>
				</div>

				<div id="div_muestra" class="hide">
					<div class="form-group estilo1" >
						<label class="col-sm-3 control-label no-padding-right" for="telefono" dir ="rtl"> Rtn  </label>
						<div class="col-sm-9">
							<input	id="id_rtn_fundacion" name="rtn_fundacion" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
						</div>
					</div>

					<div class="form-group estilo1" >
						<label class="col-sm-3 control-label no-padding-right" for="telefono" dir ="rtl"> Nombre de la Fundación  </label>
						<div class="col-sm-9">
							<input	id="id_nombre_fundacion" name="nombre_fundacion" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
						</div>
					</div>

					<div class="form-group estilo1" >
						<label class="col-sm-3 control-label no-padding-right" for="telefono" dir ="rtl"> Dirección </label>
						<div class="col-sm-9">
							<input	id="id_direccion_fundacion" name="direccion_fundacion" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
						</div>
					</div><br>
				</div>

				<div class="form-group estilo1">
					<h2 align="center"> <strong> Contacto RSC/RSE </strong></h2>
				</div>


				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="telefono" dir ="rtl"> Dirección </label>
					<div class="col-sm-9">
						<input	id="id_direccion_fundacion" name="direccion_fundacion" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div><br>


				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="titulo" dir ="rtl"> Título </label>
					<div class="col-sm-9">
					{{directiva.titulo}}
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="nombre" dir ="rtl"> Nombre </label>
					<div class="col-sm-9">
						<input	id="id_nombre" name="nombre" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="cargo" dir ="rtl"> Cargo </label>
					<div class="col-sm-9">
						<input	id="id_cargo" name="cargo" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="correo" dir ="rtl"> Correo Electrónico </label>
					<div class="col-sm-9">
						<input	id="id_correo" name="correo" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="telefono" dir ="rtl"> Teléfono </label>
					<div class="col-sm-9">
						<input	id="id_telefono" name="telefono" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="celular" dir ="rtl"> Celular </label>
					<div class="col-sm-9">
						<input	id="id_celular" name="celular" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-4 control-label no-padding-right" dir ="rtl"> Agregar Contacto Secundario </label>
					<div class="col-sm-2 control-label no-padding-right">
						<input name="check_secundario" type="checkbox" value="muestra" id="id_check_secundario" />
					</div>
				</div>


				<div id="div_muestra_secundario" class="hide">
					<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="titulo" dir ="rtl"> Título </label>
					<div class="col-sm-9">
					{{directiva.titulo}}
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="nombre" dir ="rtl"> Nombre </label>
					<div class="col-sm-9">
						<input	id="id_nombre" name="nombre" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="cargo" dir ="rtl"> Cargo </label>
					<div class="col-sm-9">
						<input	id="id_cargo" name="cargo" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="correo" dir ="rtl"> Correo Electrónico </label>
					<div class="col-sm-9">
						<input	id="id_correo" name="correo" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="telefono" dir ="rtl"> Teléfono </label>
					<div class="col-sm-9">
						<input	id="id_telefono" name="telefono" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="celular" dir ="rtl"> Celular </label>
					<div class="col-sm-9">
						<input	id="id_celular" name="celular" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div>
				</div>




				<div class="col-md-9 col-md-offset-1" >
					<div  class="col-xs-3 col-sm-5" >
						<button class="btn btn-lg btn-success btn-block" >
							<i class="icon-ok"></i>
							Siguiente
						</button>
					</div>

					<div  class="col-xs-2 col-sm-5" >
						<button type="button" class="btn btn-lg btn-danger btn-block" role="button" aria-disabled="false"><span class="ui-button-text"><i class="icon-remove bigger-110"></i>&nbsp; Cancelar Acción</span></button>
						</button>
					</div><br><br><br><br>

					
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock form %} 

{% block js %} 
<script type="text/javascript">

	$("input[name='radio']").change(function() {

		console.log('ppppp')
		if( $(this).val() == "muestra") {

			console.log('cequeo')
			$('#div_muestra').removeClass('hide')
			$('#div_muestra').show()
		}
		else{

			console.log('algo fallo')
			$('#div_muestra').hide()
		}
	});


	$('#id_check_secundario').click(function() {

		console.log('ppppp')
		if( $(this).prop('checked') ) {

			console.log('cequeo')

			$('#div_muestra_secundario').removeClass('hide')
			$('#div_muestra_secundario').show()
		}
		else{
			console.log('llll')

			console.log('algo fallo')
			$('#div_muestra_secundario').hide()
			
		}


	});

	</script>

{% endblock js %} 

aliado/templates/registrar_directiva.html
{% extends "base_registro_aliado.html" %}

{% load staticfiles %}

{% block form %} 

	{% csrf_token %}


	<fieldset><h2 align="center"> <strong> Información de Directiva </strong></h2></fieldset><br>

<div class="page-content">

	<div class="row" >
		<div class="col-md-9 col-md-offset-2" >
			<form method="post" class="form-group">
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="titulo" dir ="rtl"> Título </label>
					<div class="col-sm-9">
					{{directiva.titulo}}
					</div>
				</div>
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="nombre" dir ="rtl"> Nombre </label>
					<div class="col-sm-9">
						<input	id="id_nombre" name="nombre" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"></input>
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="cargo" dir ="rtl"> Cargo </label>
					<div class="col-sm-9">
						<input	id="id_cargo" name="cargo" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="correo" dir ="rtl"> Correo Electrónico </label>
					<div class="col-sm-9">
						<input	id="id_correo" name="correo" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="telefono" dir ="rtl"> Teléfono </label>
					<div class="col-sm-9">
						<input	id="id_telefono" name="telefono" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div>

				
				<div class="form-group estilo1" >
					<label class="col-sm-3 control-label no-padding-right" for="celular" dir ="rtl"> Celular </label>
					<div class="col-sm-9">
						<input	id="id_celular" name="celular" type="text"  class="col-xs-10 col-sm-5"  required="required" oninvalid="this.setCustomValidity('Este campo es requerido');" oninput="this.setCustomValidity('');"> </input>
					</div>
				</div>

				<div class="col-md-9 col-md-offset-1" >
					<div  class="col-xs-2 col-sm-5" >
						<button class="btn btn-lg btn-success btn-block" >
							<i class="icon-ok"></i>
							Siguiente
						</button>
					</div>

					<div  class="col-xs-2 col-sm-5" >
						<button type="button" class="btn btn-lg btn-danger btn-block" role="button" aria-disabled="false"><span class="ui-button-text"><i class="icon-remove bigger-110"></i>&nbsp; Cancelar Acción</span></button>
						</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock form %} 

aliado/templates/registrar_rubros_inversion.html
{% extends "base_registro_aliado.html" %}

{% load staticfiles %}

{% block form %} 

	{% csrf_token %}


	<fieldset><h2 align="center"> <strong> Rubros de Inversión</strong></h2></fieldset><br>

	

<div class="page-content">

	<div class="row" >
		<div class="col-md-12 col-md-offset-1" >
			<form method="post" class="form-group">

			<label>A Continuación Ingrese el rubro actual en el que invierte en educación:</label><br><br>

			
			<div class="container">
			  <table >
			   <tbody>
			      <tr>
			        <td>{{rubro}}</td>
			        <td width="40px" ></td>
			        <td><button  >Agregar</button></td>
			      		       
			      </tr>
			    </tbody>
			  </table>
			</div>


			</form>
		</div>
	</div>
</div>

{% endblock form %} 